# Generated by Django 4.1.7 on 2023-03-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_room_alter_message_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
